### ISSUE TITLE
Fail while create dashboard from InfluxDB

### ISSUE THREAD

**Issue by berekese** [chrisss404/icinga2-influxdb-grafana#2]
Hi, in first, manual is very good and its useful but I have a problem importing database, I'm sure that I am using a bad config or I am not using correctly details.
In this section -> Import Grafana dashboard and Import Grafana SNMP dashboard

I paste JSON but, should I do any changes? My databse is InfluxDB-2 and details are icinga2 and password XXXX.

When I paste JSON I get "No data" but in Icinga I get graphs without problems. 

If you could help me, it will be awesome. Thanks! Greetings.

**Comment by chrisss404** [comment]
Hi berekese!

No, you don't need to make any changes to the JSON.

Your influx credentials are needed in the following two sections:
* [Send performance data to influx](https://github.com/chrisss404/icinga2-influxdb-grafana#send-performance-data-to-influx)
* [Create new Grafana datasource](https://github.com/chrisss404/icinga2-influxdb-grafana#create-new-grafana-datasource)

HTH
Christian

**Comment by berekese** [comment]
Hi, thanks finally if I search for any host (local for example) i get data.

A question chrisss404, if I create a group with some servers, are there way to show it in Grafana on same dashboard?

Example I have 4 server "Spain", Its possible to see on same graph all servers? 

Thanks for your job.

**Comment by chrisss404** [comment]
I am sorry, but I don't know how to set this up. You may find useful information [here](https://stackoverflow.com/questions/41165488/grafana-create-groups-with-hosts).

**Comment by berekese** [comment]
Thanks, I'll look!
